//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lacashop_dbEntities : DbContext
    {
        public lacashop_dbEntities()
            : base("name=lacashop_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Customers> tbl_Customers { get; set; }
        public DbSet<tbl_ImportDetail> tbl_ImportDetail { get; set; }
        public DbSet<tbl_Imports> tbl_Imports { get; set; }
        public DbSet<tbl_ItemGroup> tbl_ItemGroup { get; set; }
        public DbSet<tbl_Items> tbl_Items { get; set; }
        public DbSet<tbl_ItemType> tbl_ItemType { get; set; }
        public DbSet<tbl_OrderDetail> tbl_OrderDetail { get; set; }
        public DbSet<tbl_Orders> tbl_Orders { get; set; }
        public DbSet<tbl_SystemContent> tbl_SystemContent { get; set; }
    }
}
