//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    
    public enum OrderStatus : int
    {
        Order = 1,
        Cancel = 2,
        Delivery = 3,
        Creating = 4
    }
}
