//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    
    [Flags]
    public enum SytemContent : int
    {
        About = 1,
        Contact = 2,
        DeliveryAndPayment = 3,
        CustomerServices = 4,
        Banner = 5
    }
}
