//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImportDetail
    {
        public int DetailID { get; set; }
        public Nullable<int> ImportID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tbl_Imports tbl_Imports { get; set; }
        public virtual tbl_Items tbl_Items { get; set; }
    }
}
