//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public tbl_Customers()
        {
            this.tbl_Orders = new HashSet<tbl_Orders>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
    
        public virtual ICollection<tbl_Orders> tbl_Orders { get; set; }
    }
}
