//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orders
    {
        public tbl_Orders()
        {
            this.tbl_OrderDetail = new HashSet<tbl_OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<OrderStatus> Status { get; set; }
    
        public virtual tbl_Customers tbl_Customers { get; set; }
        public virtual ICollection<tbl_OrderDetail> tbl_OrderDetail { get; set; }
    }
}
