//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemType
    {
        public tbl_ItemType()
        {
            this.tbl_ItemGroup = new HashSet<tbl_ItemGroup>();
        }
    
        public int ItemTypeID { get; set; }
        public string ItemTypeName { get; set; }
        public string Description { get; set; }
        public int OrderID { get; set; }
        public bool IsShow { get; set; }
    
        public virtual ICollection<tbl_ItemGroup> tbl_ItemGroup { get; set; }
    }
}
