//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemGroup
    {
        public tbl_ItemGroup()
        {
            this.OrderID = 0;
            this.tbl_Items = new HashSet<tbl_Items>();
        }
    
        public int ItemGroupID { get; set; }
        public string ItemGroupName { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public bool IsShow { get; set; }
    
        public virtual tbl_ItemType tbl_ItemType { get; set; }
        public virtual ICollection<tbl_Items> tbl_Items { get; set; }
    }
}
