//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Imports
    {
        public tbl_Imports()
        {
            this.tbl_ImportDetail = new HashSet<tbl_ImportDetail>();
        }
    
        public int ImportID { get; set; }
        public string Notes { get; set; }
        public string Supplier { get; set; }
        public string ImportUser { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
    
        public virtual ICollection<tbl_ImportDetail> tbl_ImportDetail { get; set; }
    }
}
