//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Items
    {
        public tbl_Items()
        {
            this.tbl_ImportDetail = new HashSet<tbl_ImportDetail>();
            this.tbl_OrderDetail = new HashSet<tbl_OrderDetail>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemGroupID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Images { get; set; }
        public Nullable<decimal> ViewCount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public string SearchKey { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Style { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public bool IsShow { get; set; }
        public Nullable<int> ItemCount { get; set; }
    
        public virtual ICollection<tbl_ImportDetail> tbl_ImportDetail { get; set; }
        public virtual tbl_ItemGroup tbl_ItemGroup { get; set; }
        public virtual ICollection<tbl_OrderDetail> tbl_OrderDetail { get; set; }
    }
}
